from enum import StrEnum


class EventType(StrEnum):
    """Events that describe transitions in the clinical workflow."""

    REPORT_UPLOADED = "REPORT_UPLOADED"
    REPORT_PROCESSED = "REPORT_PROCESSED"
    GENERATE_RESULT_REQUESTED = "GENERATE_RESULT_REQUESTED"
    NURSE_INPUT_REQUIRED = "NURSE_INPUT_REQUIRED"
    NURSE_INPUT_RECEIVED = "NURSE_INPUT_RECEIVED"
    OBSERVATION_READY = "OBSERVATION_READY"
    ASSESSMENT_REQUESTED = "ASSESSMENT_REQUESTED"
    ASSESSMENT_COMPLETED = "ASSESSMENT_COMPLETED"
    TREND_ANALYSIS_REQUESTED = "TREND_ANALYSIS_REQUESTED"
    TREND_ANALYSIS_COMPLETED = "TREND_ANALYSIS_COMPLETED"
    RISK_PRIORITIZATION_REQUESTED = "RISK_PRIORITIZATION_REQUESTED"
    RISK_PRIORITIZATION_COMPLETED = "RISK_PRIORITIZATION_COMPLETED"
    WORKFLOW_COMPLETED = "WORKFLOW_COMPLETED"
